export const allExercises = [
  { name: "Cardio", type: "Cardio" },
  { name: "Yoga", type: "Flexibility" },
  { name: "Pilates", type: "Flexibility" },
  { name: "CrossFit", type: "Strength" },
  { name: "HIIT", type: "Cardio" },
  { name: "Running", type: "Cardio" },
  { name: "Cycling", type: "Cardio" },
  { name: "Swimming", type: "Cardio" },
  { name: "Boxing", type: "Combat" },
  { name: "Weightlifting", type: "Strength" },
  { name: "Stretching", type: "Flexibility" },
  { name: "Bodybuilding", type: "Strength" },
  { name: "Core Training", type: "Strength" },
  { name: "Dance", type: "Cardio" },
  { name: "Kickboxing", type: "Combat" },
  { name: "TRX", type: "Strength" },
  { name: "Powerlifting", type: "Strength" },
  { name: "Zumba", type: "Cardio" },
  { name: "Calisthenics", type: "Strength" },
  { name: "Gymnastics", type: "Flexibility" },
  { name: "Rowing", type: "Cardio" },
  { name: "Martial Arts", type: "Combat" },
  { name: "Aerobics", type: "Cardio" },
  { name: "Resistance Training", type: "Strength" },
  { name: "Spin Class", type: "Cardio" },
  { name: "Plyometrics", type: "Strength" },
  { name: "Barre", type: "Flexibility" },
  { name: "Mobility Workouts", type: "Flexibility" },
];

export const months = [
  { label: "Jan", value: "January" },
  { label: "Feb", value: "February" },
  { label: "Mar", value: "March" },
  { label: "Apr", value: "April" },
  { label: "May", value: "May" },
  { label: "Jun", value: "June" },
  { label: "Jul", value: "July" },
  { label: "Aug", value: "August" },
  { label: "Sep", value: "September" },
  { label: "Oct", value: "October" },
  { label: "Nov", value: "November" },
  { label: "Dec", value: "December" },
];
