export const allExercises = (t: (key: string) => string) => [
  { name: t("exercisesList.Cardio"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Yoga"), type: t("exerciseTypes.Flexibility") },
  { name: t("exercisesList.Pilates"), type: t("exerciseTypes.Flexibility") },
  { name: t("exercisesList.CrossFit"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.HIIT"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Running"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Cycling"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Swimming"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Boxing"), type: t("exerciseTypes.Combat") },
  { name: t("exercisesList.Weightlifting"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Stretching"), type: t("exerciseTypes.Flexibility") },
  { name: t("exercisesList.Bodybuilding"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Core Training"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Dance"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Kickboxing"), type: t("exerciseTypes.Combat") },
  { name: t("exercisesList.TRX"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Powerlifting"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Zumba"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Calisthenics"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Gymnastics"), type: t("exerciseTypes.Flexibility") },
  { name: t("exercisesList.Rowing"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Martial Arts"), type: t("exerciseTypes.Combat") },
  { name: t("exercisesList.Aerobics"), type: t("exerciseTypes.Cardio") },
  {
    name: t("exercisesList.Resistance Training"),
    type: t("exerciseTypes.Strength"),
  },
  { name: t("exercisesList.Spin Class"), type: t("exerciseTypes.Cardio") },
  { name: t("exercisesList.Plyometrics"), type: t("exerciseTypes.Strength") },
  { name: t("exercisesList.Barre"), type: t("exerciseTypes.Flexibility") },
  {
    name: t("exercisesList.Mobility Workouts"),
    type: t("exerciseTypes.Flexibility"),
  },
];

export const months = (t: (key: string) => string) => [
  { label: "Jan", value: t("monthsList.January") },
  { label: "Feb", value: t("monthsList.February") },
  { label: "Mar", value: t("monthsList.March") },
  { label: "Apr", value: t("monthsList.April") },
  { label: "May", value: t("monthsList.May") },
  { label: "Jun", value: t("monthsList.June") },
  { label: "Jul", value: t("monthsList.July") },
  { label: "Aug", value: t("monthsList.August") },
  { label: "Sep", value: t("monthsList.September") },
  { label: "Oct", value: t("monthsList.October") },
  { label: "Nov", value: t("monthsList.November") },
  { label: "Dec", value: t("monthsList.December") },
];

export const roomIcons: { [key: string]: string } = {
  Cardio: "🏃‍♂️",
  Yoga: "🧘‍♀️",
  Pilates: "🤸‍♂️",
  CrossFit: "💪",
  HIIT: "🔥",
  Running: "🏃‍♀️",
  Cycling: "🚴‍♂️",
  Swimming: "🏊‍♂️",
  Boxing: "🥊",
  Weightlifting: "🏋️‍♂️",
  Stretching: "🧘‍♂️",
  Bodybuilding: "💪",
  CoreTraining: "🧘‍♀️",
  Dance: "💃",
  Kickboxing: "🥋",
  TRX: "🏋️‍♀️",
  Powerlifting: "🏋️‍♂️",
  Zumba: "🎶",
  Calisthenics: "🤸‍♀️",
  Gymnastics: "🤸‍♂️",
  Rowing: "🚣‍♂️",
  MartialArts: "🥋",
  Aerobics: "🕺",
  ResistanceTraining: "🏋️",
  SpinClass: "🚴",
  Plyometrics: "🏃‍♂️",
  Barre: "🩰",
  MobilityWorkouts: "🦵",
};
